export default STATES = [
  { name: "Alabama", _id: "AL"},
  { name: "Alaska", _id: "AK"},
  { name: "Arizona", _id: "AZ"},
  { name: "Arkansas", _id: "AR"},
  { name: "California", _id: "CA"},
  { name: "Colorado", _id: "CO"},
  { name: "Connecticut", _id: "CT"},
  { name: "Delaware", _id: "DE"},
  { name: "Florida", _id: "FL"},
  { name: "Georgia", _id: "GA"},
  { name: "Hawaii", _id: "HI"},
  { name: "Idaho", _id: "ID"},
  { name: "Illinois", _id: "IL"},
  { name: "Indiana", _id: "IN"},
  { name: "Iowa", _id: "IA"},
  { name: "Kansas", _id: "KS"},
  { name: "Kentucky", _id: "KY"},
  { name: "Louisiana", _id: "LA"},
  { name: "Maine", _id: "ME"},
  { name: "Maryland", _id: "MD"},
  { name: "Massachusetts", _id: "MA"},
  { name: "Michigan", _id: "MI"},
  { name: "Minnesota", _id: "MN"},
  { name: "Mississippi", _id: "MS"},
  { name: "Missouri", _id: "MO"},
  { name: "Montana", _id: "MT"},
  { name: "Nebraska", _id: "NE"},
  { name: "Nevada", _id: "NV"},
  { name: "New Hampshire", _id: "NH"},
  { name: "New Jersey", _id: "NJ"},
  { name: "New Mexico", _id: "NM"},
  { name: "New York", _id: "NY"},
  { name: "North Carolina", _id: "NC"},
  { name: "North Dakota", _id: "ND"},
  { name: "Ohio", _id: "OH"},
  { name: "Oklahoma", _id: "OK"},
  { name: "Oregon", _id: "OR"},
  { name: "Pennsylvania", _id: "PA"},
  { name: "Rhode Island", _id: "RI"},
  { name: "South Carolina", _id: "SC"},
  { name: "South Dakota", _id: "SD"},
  { name: "Tennessee", _id: "TN"},
  { name: "Texas", _id: "TX"},
  { name: "Utah", _id: "UT"},
  { name: "Vermont", _id: "VT"},
  { name: "Virginia", _id: "VA"},
  { name: "Washington", _id: "WA"},
  { name: "West Virginia", _id: "WV"},
  { name: "Wisconsin", _id: "WI"},
  { name: "Wyoming", _id: "WY"},
];
